
FROM python:3.8-slim-buster

COPY ./workers/uploading/requirements.txt /tmp

RUN pip install --no-cache-dir --upgrade -r /tmp/requirements.txt

# Copy repo
# COPY ./workers/uploading/src /app

WORKDIR /app
